modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT License"

[[mods]]
modId = "trailandtales_delight"
version = "0.1"
logoFile = "logo.png"
logoBlur = false
displayName = "Trail&Tales Delight"
authors = "shuixingshow, Vzling"
description = '''This mod adds more Farmer's Delight style food and tools to Trail And Tales Update'''

[[dependencies.witherstorm_delight]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.witherstorm_delight]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.witherstorm_delight]]
modId = "farmersdelight"
mandatory = true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"
