modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mixins]]
config="trailandtales_delight.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
logoFile = "logo.png"
logoBlur = false
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId = "farmersdelight"
    type="required"
    versionRange = "[0,)"
    ordering = "NONE"
    side = "BOTH"
